Test static linking
Run the tests as follows:

```
nix-shell --pure path/to/rules_haskell/shell.nix --run 'bazel test //test/vector-test
```

Assuming a checkout of rules_haskell at commit
d5203b8273fa53d68341e8bf0dc7cb8f14ebbf6c.

Then observe linker errors of the form

```
bazel-out/k8-fastbuild/bin/external/haskell_primitive__1834808089/libHSexternalZShaskellZUprimitiveZUZU1834808089ZSprimitive.a(Primitive.o):s2YJ_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziCont_zdfMonadTransContT_closure'
bazel-out/k8-fastbuild/bin/external/haskell_primitive__1834808089/libHSexternalZShaskellZUprimitiveZUZU1834808089ZSprimitive.a(Primitive.o):externalZZShaskellZZUprimitiveZZUZZU1834808089ZZSprimitive_ControlziMonadziPrimitive_zdfPrimMonadContT_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziCont_zdfMonadContT_closure'
bazel-out/k8-fastbuild/bin/external/haskell_primitive__1834808089/libHSexternalZShaskellZUprimitiveZUZU1834808089ZSprimitive.a(Primitive.o):s2YP_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziIdentity_zdfMonadTransIdentityT_closure'
```