Avoid case-sensitive workspace names
- On case-insensitive file-systems, in particular on Windows, Bazel does
    not distinguish workspaces whose names only differ by case. Stackage
    contains packages whose names only differ by case. E.g. `HSet` and
    `hset` in LTS 12.4. This causes errors of the following form on
    Windows.

    ```
    ERROR: C:/users/user/_bazel_user/glk6p2o5/external/ai_formation_hazel/hazel.bzl:172:3: Label '@haskell_HSet//:files' is duplicated in the 'files' attribute of rule 'all_hazel_packages'
    ```
- This changes modifies the way Hazel generates workspace names such
    that they become case-insensitive. This is done by appending a hash
    of the package name. Characters of different case will lead to
    different hash values.
- This change also unifies the Hazel name mangling into one extension
    file, and replaces all instances of manual name mangling by calls to
    the same name mangling functions.