Fix all_hazel_packages
The `files` attribute did not apply `_fixup_package_name` to package
names, cause errors like the following

```
ERROR: Analysis of target '@all_hazel_packages//:all-package-files' failed; build aborted: no such package '@haskell_simple-vec3//': The repository could not be resolved
```